import React,{useEffect,useRef,useState}from'react';import{createRoot}from'react-dom/client';import{ArrowDownRight,ArrowUpRight,Instagram,Linkedin,Menu,X,Play}from'lucide-react';import'./styles.css';
const R=({children,c=''})=>{let r=useRef();useEffect(()=>{let o=new IntersectionObserver(([e])=>e.isIntersecting&&e.target.classList.add('in'),{threshold:.12});o.observe(r.current);return()=>o.disconnect()},[]);return <div ref={r} className={'r '+c}>{children}</div>};
const fallback=<div className="fallback">NIKO<br/>SCHULTZ</div>;
function App(){let[m,setM]=useState(false);let go=x=>{document.getElementById(x)?.scrollIntoView({behavior:'smooth'});setM(false)};let nav=[['About','about'],['Results','results'],['Journey','journey'],['Partners','partners']];return <><header><button className="brand" onClick={()=>go('top')}>NS<span>•</span></button><nav>{nav.map(x=><button onClick={()=>go(x[1])}>{x[0]}</button>)}</nav><a className="connect" href="mailto:hello@example.com">Connect <ArrowUpRight size={15}/></a><button className="menu" onClick={()=>setM(!m)}>{m?<X/>:<Menu/>}</button></header>{m&&<aside>{nav.map(x=><button onClick={()=>go(x[1])}>{x[0]}</button>)}</aside>}
<section className="hero" id="top"><div className="copy"><p className="eyebrow">Middle distance runner · 800m</p><h1><span>NIKO</span><span className="stroke">SCHULTZ</span></h1><div className="bottom"><p>Speed with patience.<br/>Purpose in every lap.</p><button onClick={()=>go('about')}><ArrowDownRight/></button></div></div><div className="heroimg"><img src="/niko-hero.jpg"/>{fallback}</div><div className="time"><small>PERSONAL BEST</small><b>1:4×.XX</b><small>800m</small></div></section>
<section className="ticker">DISCIPLINE　✦　DRIVE　✦　DETAIL　✦　DISCIPLINE　✦　DRIVE　✦　DETAIL　✦</section>
<section className="about pad" id="about"><R><p className="eyebrow">01 / THE ATHLETE</p><h2>Built for<br/><em>the second lap.</em></h2></R><R><p className="lead">[Add Niko’s bio here: a concise statement of who he is, what drives him, and the ambition behind his racing.]</p><p>Every 800 is an argument between speed and resilience. Niko trains in that tension—finding clarity when the pace turns unforgiving.</p><a href="#journey">Read the journey <ArrowUpRight size={16}/></a></R></section>
<section className="feature"><R c="photo"><img src="/niko-track.jpg"/>{fallback}</R><R c="caption"><small>TRAINING / 2026</small><i>“The goal is simple: make the final 200 count.”</i></R></section>
<section className="pad stats" id="results"><R><p className="eyebrow">02 / BY THE NUMBERS</p><h2>A record of<br/><em>intent.</em></h2></R><div className="grid">{[['1:4×.XX','800m personal best'],['20XX','Season best year'],['XX','Career podiums'],['XX','National ranking']].map(x=><R c="stat"><b>{x[0]}</b><small>{x[1]}</small></R>)}</div><p className="note">Replace each placeholder stat with verified results.</p></section>
<section className="highlights">{[['01','[Year]','[Championship / meet title]','[Placement or result]'],['02','[Year]','[Championship / meet title]','[Placement or result]'],['03','[Year]','[Championship / meet title]','[Placement or result]']].map(x=><R c="result"><small>{x[0]}</small><small>{x[1]}</small><h3>{x[2]}</h3><p>{x[3]}</p><ArrowUpRight size={18}/></R>)}</section>
<section className="journey pad" id="journey"><R><p className="eyebrow">04 / THE JOURNEY</p><h2>Every start line<br/><em>has a story.</em></h2></R><div className="timeline">{[['NOW','[Current team / program]','Focused on the next level.'],['20XX–NOW','[College / University]','[Degree, team, or milestone]'],['20XX–20XX','[High School]','[Early achievements / coach]'],['ORIGIN','[Hometown]','Where the pursuit began.']].map((x,i)=><R c="event"><small>{x[0]}</small><div><h3>{x[1]}</h3><p>{x[2]}</p></div><small>0{i+1}</small></R>)}</div></section>
<section className="social"><R><p className="eyebrow">FOLLOW THE RUN</p><h2>Off the<br/><em>clock.</em></h2><div>{[[Instagram,'Instagram'],[Play,'TikTok'],[Linkedin,'LinkedIn']].map(([I,n])=><a href="#"><I size={18}/>{n}<ArrowUpRight size={18}/></a>)}</div></R></section>
<section className="partners pad" id="partners"><R><p className="eyebrow">05 / PARTNERS</p><h2>Powered by<br/><em>belief.</em></h2></R><R>{['YOUR SPONSOR','PARTNER TWO','PARTNER THREE'].map((x,i)=><div className="partner"><small>0{i+1}</small><b>{x}</b><ArrowUpRight size={18}/></div>)}</R></section><footer><span>© 2026 NIKO SCHULTZ</span><span>800M ATHLETE / MADE TO MOVE</span><a href="#top">BACK TO TOP</a></footer></>};createRoot(document.getElementById('root')).render(<App/>);